### ISSUE TITLE
connectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fe047610350>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fe047610350>: Failed to establish a new connection: [Errno 111] Connection refused))

### ISSUE THREAD

**Issue by zfyu** [davidgolub/SimpleQA#6]
When I run docker according to the steps in the readme, I encountered the following error. I am new to docker. And I didn't find a solution in Google search. Can you provide some help?
Thank you very much!
```
On 21000  
Reading raw line data from ../datasets/SimpleQuestions/test/object_names.txt  
On 10000  
On 20000` 
file (0x0355d060)
file (0x03584c60)
On index 1
Answering question Which genre of album is harder.....faster?
Getting all ids
genre album harder.....faster
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 257, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 257, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 397, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 487, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/src/servers/FreebaseWebServer/src/resource/freebase.py", line 31, in get
    names, num_items = fb_helper.get_names(removed_stopwords_query, num_results)
  File "/src/servers/FreebaseWebServer/src/util/freebase_helper.py", line 234, in get_names
    res = self.es.search(index=self.name_index, body=elastic_query)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 625, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 123, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fe047610350>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fe047610350>: Failed to establish a new connection: [Errno 111] Connection refused)
ERROR DECODING JSON /src/dmn/util/io_functions.lua:7: Expected value but found invalid token at character 1<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>ConnectionError: ConnectionError(&lt;urllib3.connection.HTTPConnection object at 0x7fe047610350&gt;: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(&lt;urllib3.connection.HTTPConnection object at 0x7fe047610350&gt;: Failed to establish a new connection: [Errno 111] Connection refused) // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 140601246941776,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "pV3FF3oGSfrIe7zT0qHA";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>elasticsearch.exceptions.ConnectionError</h1> 
```

**Comment by dhpollack** [comment]
I got this error too.  I think it's because it's looking up a remote freebase server which doesn't exist.  Specifically this line...

`FREEBASE_IP = 'softmaxfreebase.cloudapp.net:9200'`

https://github.com/davidgolub/SimpleQA/blob/master/servers/FreebaseWebServer/src/util/freebase_helper.py#L8

Haven't figured out a solution.
